"""Add username column

Revision ID: 13790a174142
Revises: 25a168b8cb4f
Create Date: 2026-01-08 20:20:23.494885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13790a174142'
down_revision = '25a168b8cb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
