"""increase img_url length limit

Revision ID: 3a21995d54ff
Revises: 4226122d87e4
Create Date: 2026-02-11 17:39:26.576437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a21995d54ff'
down_revision = '4226122d87e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
