"""Add can_comment to blog_posts

Revision ID: 3ed51d1aa86a
Revises: 6a2b55921039
Create Date: 2026-01-08 23:01:29.733325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed51d1aa86a'
down_revision = '6a2b55921039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_comment', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('can_comment')

    # ### end Alembic commands ###
