"""Add is_emailed flag to Messages and Notifications

Revision ID: 5f60ce2a1106
Revises: 6df0251b36ec
Create Date: 2026-03-26 17:39:34.336905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f60ce2a1106'
down_revision = '6df0251b36ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_emailed', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_emailed', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('is_emailed')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_emailed')

    # ### end Alembic commands ###
