"""Added is_deleted column to messages

Revision ID: 66abeae732b4
Revises: 3a21995d54ff
Create Date: 2026-02-14 06:06:17.531438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66abeae732b4'
down_revision = '3a21995d54ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
