"""Add related_comment_id in Notification, and DeletedAccountLog, and BannedUser models

Revision ID: 852eb84518a5
Revises: e29d7b75d02d
Create Date: 2026-02-02 21:55:29.581269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852eb84518a5'
down_revision = 'e29d7b75d02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('banned_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banned_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banned_users_email'), ['email'], unique=True)

    op.create_table('deleted_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_email', sa.String(length=255), nullable=False),
    sa.Column('original_username', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comments', ['related_comment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('related_comment_id')

    op.drop_table('deleted_accounts')
    with op.batch_alter_table('banned_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banned_users_email'))

    op.drop_table('banned_users')
    # ### end Alembic commands ###
