"""Add timestamp to comments

Revision ID: 946ded4ab165
Revises: 72cb4cb22dfe
Create Date: 2026-01-21 08:11:30.730786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946ded4ab165'
down_revision = '72cb4cb22dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
